#!/usr/bin/env python
# -*- mode: python -*-

import sys
from application import PagerPI

class Shutdown(BaseException):
    pass

class StdinPager(object):
    is_open = True

    def readline(self):
        try:
            return raw_input("pager line: ")
        except (EOFError, KeyboardInterrupt):
            raise Shutdown()

    def close(self):
        pass


class StdoutPushover(object):
    def send_message(self, message, title="Message", profile="Default"):
        sys.stdout.write("Pushover: %r [%s]" % (title, profile))
        sys.stdout.write(message)
        sys.stdout.write("\n")


def main():
    override_config = {}
    if "--local" in sys.argv:
        override_config['pager_log_host'] = 'http://localhost:8080/'
    pagerpi = PagerPI(pager=StdinPager(), override_config=override_config)
    if "--real-pushover" not in sys.argv:
        pagerpi.pushover = StdoutPushover()
        pagerpi.public_pushover = StdoutPushover()
    pagerpi.debug = True
    pagerpi.verbose = True
    pagerpi.send_addresses = lambda: None
    print "Example alert message:"
    print "x x @@ALERT F0 x G&SC1 message SVC 1729 B11 (31415) LAT/LON:-37.777, 144.444 v w x y z [resource]"
    try:
        pagerpi.main()
    except Shutdown:
        print


if __name__ == '__main__':
    main()
