#!/bin/bash

cd /home/pi/pagerpi

# update the repo as a regular user.
UPDATE_CHECK=`sudo -u pi /home/pi/pagerpi/updates/update-check`

echo $UPDATE_CHECK

python updates/scripted-updates.py

if [ "xrestart required" == "x$UPDATE_CHECK" ]; then
   systemctl --quiet is-active pager
   if [ 0 -eq $? ]; then
     systemctl restart pager
   fi
fi
