#!/usr/bin/env python
"""Update the arena-pagerpi repository and report if a restart is required.
"""
from __future__ import print_function
import sys
import traceback
from subprocess import check_call
from datetime import datetime
from os.path import join


HOME = "/home/pi"
REPO = HOME + "/pagerpi"
RELEASE_BRANCH = "master"


def git(*args):
    return check_call(["git"] + list(args), cwd=REPO)


def update_repository():
    git("fetch", "origin", RELEASE_BRANCH)
    remote = git("rev-parse", "origin/" + RELEASE_BRANCH)
    current = git("rev-parse", "HEAD")
    if remote != current:
        #git("reset", "--hard", "origin/master")
        git("merge", "origin/master")
        return True


def main():
    updated = update_repository()
    print("restart required" if updated else "up to date")


if __name__ == '__main__':
    main()
